
CPPFLAGS += -DGTEST_USE_OWN_TR1_TUPLE=0

TARGET = PROJECT

MODULEROOT = ..

MODULEPATH = PROJECT/

SUBDIRS = .

STATICS =

LIBRARIES =

PKGCONFIGS =

BINPATH = thirdparty/staging/bin

SEARCHPATH = thirdparty/staging/include \
	     flinter/output/include 

LIBRARYPATH = thirdparty/staging/lib \
	      flinter/output/lib

DESTDIR =
prefix = /usr
EXTRA_INSTALLS =
CROSS_COMPILE=

GOAL = $(EXECUTABLE)
GOALd = $(EXECUTABLEd)

include ../flinter/include.mk
